### ISSUE TITLE
Duplicate names with differing moves

### ISSUE THREAD

**Issue by Rested** [niklasf/eco#12]
One thing I came across while using the data was stuff like this 

https://github.com/niklasf/eco/blob/master/c.tsv#L331

eco | name | fen | moves |
----- | ------ | ----- | ---- |
C30 | King's Gambit Declined: Classical Variation | rnbqk1nr/ppp2ppp/3p4/2b1p3/4PP2/2P2N2/PP1P2PP/RNBQKB1R b KQkq - | e2e4 e7e5 f2f4 f8c5 g1f3 d7d6 c2c3
C30 | King's Gambit Declined: Classical Variation | rnbqk1nr/pppp1ppp/8/2b1p3/4PP2/8/PPPP2PP/RNBQKBNR w KQkq - | e2e4 e7e5 f2f4 f8c5

Where two or lines would have the same name yet one would have additional continuations/moves. I'm not sure whether this is intended or not or if this is even a problem but when I see 

eco | name | fen | moves |
----- | ------ | ----- | ---- |
C30 | King's Gambit Declined: Classical Variation, Rotlewi Countergambit | rnbqk1nr/ppp2ppp/3p4/2b1p3/1P2PP2/5N2/P1PP2PP/RNBQKB1R b KQkq - | e2e4 e7e5 f2f4 f8c5 g1f3 d7d6 b2b4

I feel like `King's Gambit Declined: Classical Variation` should be `e2e4 e7e5 f2f4 f8c5` since it is a strict subset of `e2e4 e7e5 f2f4 f8c5 g1f3 d7d6 b2b4`. Whereas `e2e4 e7e5 f2f4 f8c5 g1f3 d7d6 c2c3` should perhaps be called e.g. `King's Gambit Declined: Classical Variation, Classical Continuation` or something. 

Would be interested to know your thoughts!

**Comment by niklasf** [comment]
To browse the lines: https://lichess.org/study/OJUS3ngt

I'd say the recommended way to classify openings is to play the game in reverse until the first matching position is found. So in general there might be legit cases where two positions should explicitly have the same name. For example, suppose the longer line has the name, and there's a shorter line that should also already have the name, but that can be avoided by transposition.

I am not sure about this particular case. I don't see any reasonable transpositions avoiding `rnbqk1nr/pppp1ppp/8/2b1p3/4PP2/8/PPPP2PP/RNBQKBNR w KQkq -` (position after the shorter line). `Classical Continuation` feels a bit artificial. So perhaps just remove the longer Classical entry?

**Comment by niklasf** [comment]
Just as I post that ... perhaps we should keep it due to 1. e4 e5 2. c3 Bc5 3. f4 d6 4. Nf3?

**Comment by Rested** [comment]
Ah I see what you mean, and that does make a lot of sense, I suppose it is me imagining it as a pure tree where the parent node in terms of name (e.g. KGD: Classical Variation) is also a parent in terms of moves. 

`1. e4 e5 2. c3 Bc5 3. f4 d6 4. Nf3`
Does seem to be a perfectly reasonable transposition from the MacLeod Attack

The point you raise about what would make a duplicate invalid is interesting, I wonder if it would make sense to add something along those lines to `lint.py`.  By e.g. warning if there is not some transposition from the which avoids a shorter line of the same name and retains abs(eval) < 1 throughout. However I imagine that would add a fair bit of bloat to the repo and not sure how useful it would be.
